import Head from "next/head";
import { GetStaticProps } from "next";
import { getNews } from "@/utils/api";
import { formatDistance } from "date-fns";
import { Header } from "@/components/Header";
import Link from "next/link";

interface Article {
  title: string;
  description: string;
  url: string;
  urlToImage: string;
  publishedAt: string;
  source: {
    name: string;
  };
}

export interface News {
  totalResults: number;
  articles: Article[];
}

interface Props {
  news: News;
}

export default function Home({ news }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className="w-screen h-auto flex flex-col gap-7 items-center">
        <h1 className="text-5xl mt-5">News</h1>

        {news.articles.map((article) => (
          <Link
            href={article.url}
            key={article.title}
            className="max-w-lg h-auto bg-black"
          >
            <div>
              <img
                src={article.urlToImage}
                alt={article.title}
                className="w-full h-full"
              />
              <div className="mt-2 p-2">
                <h2 className="text-lg font-bold">{article.title}</h2>
                <p className="mt-3">{article.description}</p>
                <strong>
                  {formatDistance(new Date(article.publishedAt), new Date(), {
                    addSuffix: true,
                  })}
                </strong>
              </div>
            </div>
          </Link>
        ))}
      </main>
    </>
  );
}

export const getStaticProps: GetStaticProps<Props> = async () => {
  const news = await getNews("us");
  return {
    props: {
      news,
    },
    revalidate: 60 * 60,
  };
};
